<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ja">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Style-Type" content="text/css">
        <meta http-equiv="Content-Script-Type" content="text/javascript">
        <meta name="keywords" content="">
        <meta name="title" content="Sample">
        <meta name="author" content="">
        <meta name="copyright" content="2008 Zend">
        <title>Captain List</title>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <script type="text/javascript" src="/js/jquery-2.1.3.min.js"></script>
        <script type="text/javascript" src="/js/jquery.tmpl.js"></script>
        <?php echo $this->headScript() ?>
    </head>
    <body>
         <?php echo $this->layout()->content; ?>
    </body>
</html>