<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>
</head>
<body>
  <div class="container">
      <?php if(strtolower($this->message)=="page not found") : ?>
          <div class="col-lg-12 text-center">
                <h1><span class="text-xxxl text-light">404 <i class="fa fa-search-minus text-primary"></i></span></h1>
                <h2 class="text-light">This page does not exist</h2>
              </div>
        <?php else: ?>
          <div class="col-lg-12 text-center">
                <h1><span class="text-xxxl text-light">500 <i class="fa fa-exclamation-circle text-danger"></i></span></h1>
                <h2 class="text-light">Oops! Application Error</h2>
          </div>
        <?php endif;?>
      

  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <p><?php echo $this->exception->getTraceAsString() ?>
  </p>

  <h3>Request Parameters:</h3>
  <p><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </p>

  <?php endif ?>
  <p>You can go to home page from menu</p>
  </div>
</body>
</html>
